// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs69xFoE6ZQwNfrfvcqTuU8oH-QIPFeAQ',
    appId: '1:784931302196:web:68fee79105dee646e5d361',
    messagingSenderId: '784931302196',
    projectId: 'ai-language-7f113',
    authDomain: 'ai-language-7f113.firebaseapp.com',
    storageBucket: 'ai-language-7f113.firebasestorage.app',
    measurementId: 'G-WNEDY7BYVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvjUVurVsKV5yMhahqFTOhFvNpN9mI0lk',
    appId: '1:784931302196:android:4c21b6eccd34d71fe5d361',
    messagingSenderId: '784931302196',
    projectId: 'ai-language-7f113',
    storageBucket: 'ai-language-7f113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbrvAMHCF1molUlPuL8BmiKLqC3dOQl6U',
    appId: '1:784931302196:ios:ffb8f13e54cccce1e5d361',
    messagingSenderId: '784931302196',
    projectId: 'ai-language-7f113',
    storageBucket: 'ai-language-7f113.firebasestorage.app',
    iosBundleId: 'com.example.aiLanguage',
  );
}
